In [9]:
import osqp
import numpy as np
import matplotlib.pyplot as plt
from scipy import sparse


[0.6 1.1 2.1 3.1 4.1 5.1 6.1 7.1 8.1 9.1]### example from osqp.org
https://osqp.org/docs/examples/setup-and-solve.html

Consider the following QP
 \begin{split}\begin{array}{ll}
  \mbox{minimize} & \frac{1}{2} x^T \begin{bmatrix}4 & 1\\ 1 & 2 \end{bmatrix} x + \begin{bmatrix}1 \\ 1\end{bmatrix}^T x \\
  \mbox{subject to} & \begin{bmatrix}1 \\ 0 \\ 0\end{bmatrix} \leq \begin{bmatrix} 1 & 1\\ 1 & 0\\ 0 & 1\end{bmatrix} x \leq  \begin{bmatrix}1 \\ 0.7 \\ 0.7\end{bmatrix}
\end{array}\end{split}

In [10]:
P = sparse.csc_matrix([[4,1],[1,2]])
q = np.array([1,1])
A = sparse.csc_matrix([[1,1],[1,0],[0,1]])
l = np.array([1,0,0])
u = np.array([1,0.7,0.7])

prob = osqp.OSQP()
prob.setup(P,q,A,l,u,alpha = 1.0)
res = prob.solve()
print(res.x,res.y)

[[4 1]
 [1 2]]
  (0, 0)	4
  (1, 0)	1
  (0, 1)	1
  (1, 1)	2
[1 1]
  (0, 0)	1
  (1, 0)	1
  (0, 1)	1
  (2, 1)	1
[1 0 0]
[1.  0.7 0.7]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2, constraints m = 3
          nnz(P) + nnz(A) = 7
settings: linear system solver = qdldl,
          eps_abs = 1.0e-03, eps_rel = 1.0e-03,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.00, max_iter = 4000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: off, time_limit: off

iter   objective    pri res    dua res    rho        time
   1  -4.9384e-03   1.00e+00   2.00e+02   1.00

## Least-squares

Consider the following constrained least-squares problem
\begin{split}\begin{array}{ll}
  \mbox{minimize} & \frac{1}{2} \|Ax - b\|_2^2 \\
  \mbox{subject to} & 0 \leq x \leq 1
\end{array}\end{split}

The problem has the following equivalent form
\begin{split}\begin{array}{ll}
  \mbox{minimize} & \frac{1}{2} y^T y \\
  \mbox{subject to} & y = A x - b \\
                    & 0 \le x \le 1
\end{array}\end{split}


In [14]:
import osqp
import numpy as np
import scipy as sp
from scipy import sparse

# Generate problem data
sp.random.seed(1)
m = 30
n = 20
Ad = sparse.random(m, n, density=0.7, format='csc')
b = np.random.randn(m)

# OSQP data
P = sparse.block_diag([sparse.csc_matrix((n, n)), sparse.eye(m)], format='csc')
q = np.zeros(n+m)
A = sparse.vstack([
        sparse.hstack([Ad, -sparse.eye(m)]),
        sparse.hstack([sparse.eye(n), sparse.csc_matrix((n, m))])], format='csc')
l = np.hstack([b, np.zeros(n)])
u = np.hstack([b, np.ones(n)])

print(P)
print(q)
print(A)
print(l)
print(u)


# Create an OSQP object
prob = osqp.OSQP()

# Setup workspace
prob.setup(P, q, A, l, u)

# Solve problem
res = prob.solve()

print(res.x)
print(res.y)

  (20, 20)	1.0
  (21, 21)	1.0
  (22, 22)	1.0
  (23, 23)	1.0
  (24, 24)	1.0
  (25, 25)	1.0
  (26, 26)	1.0
  (27, 27)	1.0
  (28, 28)	1.0
  (29, 29)	1.0
  (30, 30)	1.0
  (31, 31)	1.0
  (32, 32)	1.0
  (33, 33)	1.0
  (34, 34)	1.0
  (35, 35)	1.0
  (36, 36)	1.0
  (37, 37)	1.0
  (38, 38)	1.0
  (39, 39)	1.0
  (40, 40)	1.0
  (41, 41)	1.0
  (42, 42)	1.0
  (43, 43)	1.0
  (44, 44)	1.0
  (45, 45)	1.0
  (46, 46)	1.0
  (47, 47)	1.0
  (48, 48)	1.0
  (49, 49)	1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
  (0, 0)	0.40239251985773583
  (1, 0)	0.31476568732401644
  (2, 0)	0.1065838767888011
  (3, 0)	0.1747201501089225
  (4, 0)	0.27411977516685215
  (5, 0)	0.013136356923072245
  (6, 0)	0.3950968688899732
  (8, 0)	0.6993076236968142
  (9, 0)	0.99675342520821
  (11, 0)	0.08010364380604929
  (12, 0)	0.06780693434095375
  (13, 0)	0.0030179566195963625
  (14, 0)	0.6243367024026759
  (16, 0)	0.43530595